// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * business API
 *
 * API для модуля business
 *
 * API version: 1.0.0
 */

package businessgenerated

import (
	"context"
	"net/http"
)



// BusinessesAPIRouter defines the required methods for binding the api requests to a responses for the BusinessesAPI
// The BusinessesAPIRouter implementation should parse necessary information from the http request,
// pass the data to a BusinessesAPIServicer to perform the required actions, then write the service results to the http response.
type BusinessesAPIRouter interface { 
	BusinessesPost(http.ResponseWriter, *http.Request)
	BusinessesIdGet(http.ResponseWriter, *http.Request)
	BusinessesIdPut(http.ResponseWriter, *http.Request)
}


// BusinessesAPIServicer defines the api actions for the BusinessesAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type BusinessesAPIServicer interface { 
	BusinessesPost(context.Context, CreateBusinessRequest) (ImplResponse, error)
	BusinessesIdGet(context.Context, int64) (ImplResponse, error)
	BusinessesIdPut(context.Context, int64, UpdateBusinessRequest) (ImplResponse, error)
}
