// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * business API
 *
 * API для модуля business
 *
 * API version: 1.0.0
 */

package businessgenerated

import (
	"context"
	"net/http"
	"errors"
)

// BusinessesAPIService is a service that implements the logic for the BusinessesAPIServicer
// This service should implement the business logic for every endpoint for the BusinessesAPI API.
// Include any external packages or services that will be required by this service.
type BusinessesAPIService struct {
}

// NewBusinessesAPIService creates a default api service
func NewBusinessesAPIService() *BusinessesAPIService {
	return &BusinessesAPIService{}
}

// BusinessesPost - Создать бизнес
func (s *BusinessesAPIService) BusinessesPost(ctx context.Context, createBusinessRequest CreateBusinessRequest) (ImplResponse, error) {
	// TODO - update BusinessesPost with the required logic for this service method.
	// Add api_businesses_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Business{}) or use other options such as http.Ok ...
	// return Response(201, Business{}), nil

	// TODO: Uncomment the next line to return response Response(400, BusinessesPost400Response{}) or use other options such as http.Ok ...
	// return Response(400, BusinessesPost400Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("BusinessesPost method not implemented")
}

// BusinessesIdGet - Получить бизнес по ID
func (s *BusinessesAPIService) BusinessesIdGet(ctx context.Context, id int64) (ImplResponse, error) {
	// TODO - update BusinessesIdGet with the required logic for this service method.
	// Add api_businesses_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Business{}) or use other options such as http.Ok ...
	// return Response(200, Business{}), nil

	// TODO: Uncomment the next line to return response Response(404, BusinessesIdGet404Response{}) or use other options such as http.Ok ...
	// return Response(404, BusinessesIdGet404Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("BusinessesIdGet method not implemented")
}

// BusinessesIdPut - Обновить бизнес
func (s *BusinessesAPIService) BusinessesIdPut(ctx context.Context, id int64, updateBusinessRequest UpdateBusinessRequest) (ImplResponse, error) {
	// TODO - update BusinessesIdPut with the required logic for this service method.
	// Add api_businesses_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Business{}) or use other options such as http.Ok ...
	// return Response(200, Business{}), nil

	// TODO: Uncomment the next line to return response Response(404, BusinessesIdGet404Response{}) or use other options such as http.Ok ...
	// return Response(404, BusinessesIdGet404Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("BusinessesIdPut method not implemented")
}
