// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * business API
 *
 * API для модуля business
 *
 * API version: 1.0.0
 */

package businessgenerated

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// BusinessesAPIController binds http requests to an api service and writes the service results to the http response
type BusinessesAPIController struct {
	service BusinessesAPIServicer
	errorHandler ErrorHandler
}

// BusinessesAPIOption for how the controller is set up.
type BusinessesAPIOption func(*BusinessesAPIController)

// WithBusinessesAPIErrorHandler inject ErrorHandler into controller
func WithBusinessesAPIErrorHandler(h ErrorHandler) BusinessesAPIOption {
	return func(c *BusinessesAPIController) {
		c.errorHandler = h
	}
}

// NewBusinessesAPIController creates a default api controller
func NewBusinessesAPIController(s BusinessesAPIServicer, opts ...BusinessesAPIOption) *BusinessesAPIController {
	controller := &BusinessesAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the BusinessesAPIController
func (c *BusinessesAPIController) Routes() Routes {
	return Routes{
		"BusinessesPost": Route{
			"BusinessesPost",
			strings.ToUpper("Post"),
			"/api/v1/businesses",
			c.BusinessesPost,
		},
		"BusinessesIdGet": Route{
			"BusinessesIdGet",
			strings.ToUpper("Get"),
			"/api/v1/businesses/{id}",
			c.BusinessesIdGet,
		},
		"BusinessesIdPut": Route{
			"BusinessesIdPut",
			strings.ToUpper("Put"),
			"/api/v1/businesses/{id}",
			c.BusinessesIdPut,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the BusinessesAPIController
func (c *BusinessesAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"BusinessesPost",
			strings.ToUpper("Post"),
			"/api/v1/businesses",
			c.BusinessesPost,
		},
		Route{
			"BusinessesIdGet",
			strings.ToUpper("Get"),
			"/api/v1/businesses/{id}",
			c.BusinessesIdGet,
		},
		Route{
			"BusinessesIdPut",
			strings.ToUpper("Put"),
			"/api/v1/businesses/{id}",
			c.BusinessesIdPut,
		},
	}
}



// BusinessesPost - Создать бизнес
func (c *BusinessesAPIController) BusinessesPost(w http.ResponseWriter, r *http.Request) {
	var createBusinessRequestParam CreateBusinessRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&createBusinessRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertCreateBusinessRequestRequired(createBusinessRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertCreateBusinessRequestConstraints(createBusinessRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.BusinessesPost(r.Context(), createBusinessRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// BusinessesIdGet - Получить бизнес по ID
func (c *BusinessesAPIController) BusinessesIdGet(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam, err := parseNumericParameter[int64](
		params["id"],
		WithRequire[int64](parseInt64),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Param: "id", Err: err}, nil)
		return
	}
	result, err := c.service.BusinessesIdGet(r.Context(), idParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// BusinessesIdPut - Обновить бизнес
func (c *BusinessesAPIController) BusinessesIdPut(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	idParam, err := parseNumericParameter[int64](
		params["id"],
		WithRequire[int64](parseInt64),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Param: "id", Err: err}, nil)
		return
	}
	var updateBusinessRequestParam UpdateBusinessRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&updateBusinessRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertUpdateBusinessRequestRequired(updateBusinessRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertUpdateBusinessRequestConstraints(updateBusinessRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.BusinessesIdPut(r.Context(), idParam, updateBusinessRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
