// Package businessgenerated provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package businessgenerated

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Business defines model for Business.
type Business struct {
	CreatedAt   time.Time  `json:"createdAt"`
	DeletedAt   *time.Time `json:"deletedAt"`
	Description *string    `json:"description"`
	Id          uint64     `json:"id"`

	// IsWorking Флаг активности
	IsWorking       *bool               `json:"isWorking,omitempty"`
	LogoId          *string             `json:"logoId"`
	Name            string              `json:"name"`
	OwnerEmail      openapi_types.Email `json:"ownerEmail"`
	OwnerFirstName  string              `json:"ownerFirstName"`
	OwnerId         *uint64             `json:"ownerId"`
	OwnerLastName   string              `json:"ownerLastName"`
	OwnerMiddleName *string             `json:"ownerMiddleName"`
	OwnerPhone      string              `json:"ownerPhone"`
	UpdatedAt       time.Time           `json:"updatedAt"`
}

// CreateBusinessRequest defines model for CreateBusinessRequest.
type CreateBusinessRequest struct {
	Description     *string             `json:"description"`
	Name            string              `json:"name"`
	OwnerEmail      openapi_types.Email `json:"ownerEmail"`
	OwnerFirstName  string              `json:"ownerFirstName"`
	OwnerLastName   string              `json:"ownerLastName"`
	OwnerMiddleName *string             `json:"ownerMiddleName"`
	OwnerPhone      string              `json:"ownerPhone"`

	// Password Пароль для авторизации
	Password string `json:"password"`

	// PasswordConfirmation Подтверждение пароля
	PasswordConfirmation string `json:"passwordConfirmation"`
}

// CreateBusinessResponse defines model for CreateBusinessResponse.
type CreateBusinessResponse struct {
	Data    Business `json:"data"`
	Message string   `json:"message"`
}

// UpdateBusinessRequest defines model for UpdateBusinessRequest.
type UpdateBusinessRequest struct {
	Description *string `json:"description"`

	// IsWorking Флаг активности
	IsWorking       *bool                `json:"isWorking"`
	LogoId          *string              `json:"logoId"`
	Name            *string              `json:"name"`
	OwnerEmail      *openapi_types.Email `json:"ownerEmail"`
	OwnerFirstName  *string              `json:"ownerFirstName"`
	OwnerId         *uint64              `json:"ownerId"`
	OwnerLastName   *string              `json:"ownerLastName"`
	OwnerMiddleName *string              `json:"ownerMiddleName"`
	OwnerPhone      *string              `json:"ownerPhone"`
}

// ValidationErrorDetail defines model for ValidationErrorDetail.
type ValidationErrorDetail struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// BusinessNotFound defines model for BusinessNotFound.
type BusinessNotFound struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Details []ValidationErrorDetail `json:"details"`
	Error   string                  `json:"error"`
	Message string                  `json:"message"`
}

// PostBusinessJSONRequestBody defines body for PostBusiness for application/json ContentType.
type PostBusinessJSONRequestBody = CreateBusinessRequest

// PutBusinessIdJSONRequestBody defines body for PutBusinessId for application/json ContentType.
type PutBusinessIdJSONRequestBody = UpdateBusinessRequest
