// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * business API
 *
 * API для модуля business
 *
 * API version: 1.0.0
 */

package businessgenerated




type UpdateBusinessRequest struct {

	Name *string `json:"name,omitempty"`

	Description *string `json:"description,omitempty"`

	OwnerFirstName *string `json:"ownerFirstName,omitempty"`

	OwnerLastName *string `json:"ownerLastName,omitempty"`

	OwnerMiddleName *string `json:"ownerMiddleName,omitempty"`

	OwnerEmail *string `json:"ownerEmail,omitempty"`

	OwnerPhone *string `json:"ownerPhone,omitempty"`

	LogoId *string `json:"logoId,omitempty"`

	// Флаг активности
	IsWorking *bool `json:"isWorking,omitempty"`

	OwnerId *int32 `json:"ownerId,omitempty"`
}

// AssertUpdateBusinessRequestRequired checks if the required fields are not zero-ed
func AssertUpdateBusinessRequestRequired(obj UpdateBusinessRequest) error {
	return nil
}

// AssertUpdateBusinessRequestConstraints checks if the values respects the defined constraints
func AssertUpdateBusinessRequestConstraints(obj UpdateBusinessRequest) error {
	return nil
}
