// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * business API
 *
 * API для модуля business
 *
 * API version: 1.0.0
 */

package businessgenerated




type CreateBusinessRequest struct {

	Name string `json:"name"`

	Description *string `json:"description,omitempty"`

	OwnerFirstName string `json:"ownerFirstName"`

	OwnerLastName string `json:"ownerLastName"`

	OwnerMiddleName *string `json:"ownerMiddleName,omitempty"`

	OwnerEmail string `json:"ownerEmail"`

	OwnerPhone string `json:"ownerPhone"`

	LogoId *string `json:"logoId,omitempty"`

	// Флаг активности
	IsWorking bool `json:"isWorking,omitempty"`

	OwnerId *int32 `json:"ownerId,omitempty"`
}

// AssertCreateBusinessRequestRequired checks if the required fields are not zero-ed
func AssertCreateBusinessRequestRequired(obj CreateBusinessRequest) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"ownerFirstName": obj.OwnerFirstName,
		"ownerLastName": obj.OwnerLastName,
		"ownerEmail": obj.OwnerEmail,
		"ownerPhone": obj.OwnerPhone,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateBusinessRequestConstraints checks if the values respects the defined constraints
func AssertCreateBusinessRequestConstraints(obj CreateBusinessRequest) error {
	return nil
}
