// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * business API
 *
 * API для модуля business
 *
 * API version: 1.0.0
 */

package businessgenerated




type ErrorDetail struct {

	Field string `json:"field,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertErrorDetailRequired checks if the required fields are not zero-ed
func AssertErrorDetailRequired(obj ErrorDetail) error {
	return nil
}

// AssertErrorDetailConstraints checks if the values respects the defined constraints
func AssertErrorDetailConstraints(obj ErrorDetail) error {
	return nil
}
