// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * business API
 *
 * API для модуля business
 *
 * API version: 1.0.0
 */

package businessgenerated




type BusinessesPost400Response struct {

	Error string `json:"error,omitempty"`

	Message string `json:"message,omitempty"`

	Details []ErrorDetail `json:"details,omitempty"`
}

// AssertBusinessesPost400ResponseRequired checks if the required fields are not zero-ed
func AssertBusinessesPost400ResponseRequired(obj BusinessesPost400Response) error {
	for _, el := range obj.Details {
		if err := AssertErrorDetailRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertBusinessesPost400ResponseConstraints checks if the values respects the defined constraints
func AssertBusinessesPost400ResponseConstraints(obj BusinessesPost400Response) error {
	for _, el := range obj.Details {
		if err := AssertErrorDetailConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
