// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * business API
 *
 * API для модуля business
 *
 * API version: 1.0.0
 */

package businessgenerated




type BusinessesIdGet404Response struct {

	Error string `json:"error,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertBusinessesIdGet404ResponseRequired checks if the required fields are not zero-ed
func AssertBusinessesIdGet404ResponseRequired(obj BusinessesIdGet404Response) error {
	return nil
}

// AssertBusinessesIdGet404ResponseConstraints checks if the values respects the defined constraints
func AssertBusinessesIdGet404ResponseConstraints(obj BusinessesIdGet404Response) error {
	return nil
}
