// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * employee API
 *
 * API для модуля employee
 *
 * API version: 1.0.0
 */

package employeegenerated

import (
	"context"
	"net/http"
)



// EmployeesAPIRouter defines the required methods for binding the api requests to a responses for the EmployeesAPI
// The EmployeesAPIRouter implementation should parse necessary information from the http request,
// pass the data to a EmployeesAPIServicer to perform the required actions, then write the service results to the http response.
type EmployeesAPIRouter interface { 
	EmployeesGet(http.ResponseWriter, *http.Request)
	EmployeesPost(http.ResponseWriter, *http.Request)
	EmployeesIdGet(http.ResponseWriter, *http.Request)
	EmployeesIdPut(http.ResponseWriter, *http.Request)
	EmployeesIdDelete(http.ResponseWriter, *http.Request)
}


// EmployeesAPIServicer defines the api actions for the EmployeesAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type EmployeesAPIServicer interface { 
	EmployeesGet(context.Context, int32, int32) (ImplResponse, error)
	EmployeesPost(context.Context, CreateEmployeeRequest) (ImplResponse, error)
	EmployeesIdGet(context.Context, int64) (ImplResponse, error)
	EmployeesIdPut(context.Context, int64, UpdateEmployeeRequest) (ImplResponse, error)
	EmployeesIdDelete(context.Context, int64) (ImplResponse, error)
}
