// Package employeegenerated provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package employeegenerated

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateEmployeeRequestRole.
const (
	CreateEmployeeRequestRoleAdmin   CreateEmployeeRequestRole = "admin"
	CreateEmployeeRequestRoleOwner   CreateEmployeeRequestRole = "owner"
	CreateEmployeeRequestRoleRegular CreateEmployeeRequestRole = "regular"
)

// Defines values for CreateEmployeeRequestStatus.
const (
	CreateEmployeeRequestStatusActive     CreateEmployeeRequestStatus = "active"
	CreateEmployeeRequestStatusIll        CreateEmployeeRequestStatus = "ill"
	CreateEmployeeRequestStatusOnboarding CreateEmployeeRequestStatus = "onboarding"
	CreateEmployeeRequestStatusVacation   CreateEmployeeRequestStatus = "vacation"
)

// Defines values for EmployeeRole.
const (
	EmployeeRoleAdmin   EmployeeRole = "admin"
	EmployeeRoleOwner   EmployeeRole = "owner"
	EmployeeRoleRegular EmployeeRole = "regular"
)

// Defines values for EmployeeStatus.
const (
	EmployeeStatusActive     EmployeeStatus = "active"
	EmployeeStatusIll        EmployeeStatus = "ill"
	EmployeeStatusOnboarding EmployeeStatus = "onboarding"
	EmployeeStatusVacation   EmployeeStatus = "vacation"
)

// Defines values for UpdateEmployeeRequestRole.
const (
	Admin   UpdateEmployeeRequestRole = "admin"
	Owner   UpdateEmployeeRequestRole = "owner"
	Regular UpdateEmployeeRequestRole = "regular"
)

// Defines values for UpdateEmployeeRequestStatus.
const (
	Active     UpdateEmployeeRequestStatus = "active"
	Ill        UpdateEmployeeRequestStatus = "ill"
	Onboarding UpdateEmployeeRequestStatus = "onboarding"
	Vacation   UpdateEmployeeRequestStatus = "vacation"
)

// CreateEmployeeRequest defines model for CreateEmployeeRequest.
type CreateEmployeeRequest struct {
	AvatarUrl  *string                      `json:"avatarUrl"`
	BirthDate  *openapi_types.Date          `json:"birthDate"`
	Email      openapi_types.Email          `json:"email"`
	FirstName  string                       `json:"firstName"`
	HiredAt    *time.Time                   `json:"hiredAt"`
	LastName   string                       `json:"lastName"`
	MiddleName *string                      `json:"middleName"`
	Phone      string                       `json:"phone"`
	Position   *string                      `json:"position"`
	Role       *CreateEmployeeRequestRole   `json:"role,omitempty"`
	Status     *CreateEmployeeRequestStatus `json:"status"`
}

// CreateEmployeeRequestRole defines model for CreateEmployeeRequest.Role.
type CreateEmployeeRequestRole string

// CreateEmployeeRequestStatus defines model for CreateEmployeeRequest.Status.
type CreateEmployeeRequestStatus string

// Employee defines model for Employee.
type Employee struct {
	AddedAt    *time.Time          `json:"addedAt,omitempty"`
	AvatarUrl  *string             `json:"avatarUrl"`
	BirthDate  *openapi_types.Date `json:"birthDate"`
	CreatedAt  *time.Time          `json:"createdAt,omitempty"`
	CreatedBy  *uint64             `json:"createdBy"`
	Email      openapi_types.Email `json:"email"`
	FiredAt    *time.Time          `json:"firedAt"`
	FirstName  string              `json:"firstName"`
	HiredAt    *time.Time          `json:"hiredAt"`
	Id         uint64              `json:"id"`
	LastName   string              `json:"lastName"`
	MiddleName *string             `json:"middleName"`
	Phone      string              `json:"phone"`
	Position   *string             `json:"position"`
	Role       *EmployeeRole       `json:"role,omitempty"`
	Status     *EmployeeStatus     `json:"status,omitempty"`
	UpdatedAt  *time.Time          `json:"updatedAt,omitempty"`
}

// EmployeeRole defines model for Employee.Role.
type EmployeeRole string

// EmployeeStatus defines model for Employee.Status.
type EmployeeStatus string

// EmployeeListResponse defines model for EmployeeListResponse.
type EmployeeListResponse struct {
	Data       *[]Employee `json:"data,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Field   *string `json:"field,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Limit *int `json:"limit,omitempty"`
	Page  *int `json:"page,omitempty"`
	Pages *int `json:"pages,omitempty"`
	Total *int `json:"total,omitempty"`
}

// UpdateEmployeeRequest defines model for UpdateEmployeeRequest.
type UpdateEmployeeRequest struct {
	AvatarUrl  *string                      `json:"avatarUrl"`
	BirthDate  *openapi_types.Date          `json:"birthDate"`
	Email      *openapi_types.Email         `json:"email"`
	FiredAt    *time.Time                   `json:"firedAt"`
	FirstName  *string                      `json:"firstName,omitempty"`
	HiredAt    *time.Time                   `json:"hiredAt"`
	LastName   *string                      `json:"lastName,omitempty"`
	MiddleName *string                      `json:"middleName"`
	Phone      *string                      `json:"phone"`
	Position   *string                      `json:"position"`
	Role       *UpdateEmployeeRequestRole   `json:"role,omitempty"`
	Status     *UpdateEmployeeRequestStatus `json:"status"`
}

// UpdateEmployeeRequestRole defines model for UpdateEmployeeRequest.Role.
type UpdateEmployeeRequestRole string

// UpdateEmployeeRequestStatus defines model for UpdateEmployeeRequest.Status.
type UpdateEmployeeRequestStatus string

// EmployeeNotFound defines model for EmployeeNotFound.
type EmployeeNotFound struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Details *[]ErrorDetail `json:"details,omitempty"`
	Error   *string        `json:"error,omitempty"`
	Message *string        `json:"message,omitempty"`
}

// GetEmployeesParams defines parameters for GetEmployees.
type GetEmployeesParams struct {
	// Page Номер страницы
	Page *int32 `form:"page,omitempty" json:"page,omitempty"`

	// Limit Количество сотрудников на странице
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostEmployeesJSONRequestBody defines body for PostEmployees for application/json ContentType.
type PostEmployeesJSONRequestBody = CreateEmployeeRequest

// PutEmployeesIdJSONRequestBody defines body for PutEmployeesId for application/json ContentType.
type PutEmployeesIdJSONRequestBody = UpdateEmployeeRequest
