// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * employee API
 *
 * API для модуля employee
 *
 * API version: 1.0.0
 */

package employeegenerated




type EmployeesIdGet404Response struct {

	Error string `json:"error,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertEmployeesIdGet404ResponseRequired checks if the required fields are not zero-ed
func AssertEmployeesIdGet404ResponseRequired(obj EmployeesIdGet404Response) error {
	return nil
}

// AssertEmployeesIdGet404ResponseConstraints checks if the values respects the defined constraints
func AssertEmployeesIdGet404ResponseConstraints(obj EmployeesIdGet404Response) error {
	return nil
}
