// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * employee API
 *
 * API для модуля employee
 *
 * API version: 1.0.0
 */

package employeegenerated




type EmployeeListResponse struct {

	Data []Employee `json:"data,omitempty"`

	Pagination Pagination `json:"pagination,omitempty"`
}

// AssertEmployeeListResponseRequired checks if the required fields are not zero-ed
func AssertEmployeeListResponseRequired(obj EmployeeListResponse) error {
	for _, el := range obj.Data {
		if err := AssertEmployeeRequired(el); err != nil {
			return err
		}
	}
	if err := AssertPaginationRequired(obj.Pagination); err != nil {
		return err
	}
	return nil
}

// AssertEmployeeListResponseConstraints checks if the values respects the defined constraints
func AssertEmployeeListResponseConstraints(obj EmployeeListResponse) error {
	for _, el := range obj.Data {
		if err := AssertEmployeeConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertPaginationConstraints(obj.Pagination); err != nil {
		return err
	}
	return nil
}
