// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * employee API
 *
 * API для модуля employee
 *
 * API version: 1.0.0
 */

package employeegenerated




type EmployeesPost400Response struct {

	Error string `json:"error,omitempty"`

	Message string `json:"message,omitempty"`

	Details []ErrorDetail `json:"details,omitempty"`
}

// AssertEmployeesPost400ResponseRequired checks if the required fields are not zero-ed
func AssertEmployeesPost400ResponseRequired(obj EmployeesPost400Response) error {
	for _, el := range obj.Details {
		if err := AssertErrorDetailRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertEmployeesPost400ResponseConstraints checks if the values respects the defined constraints
func AssertEmployeesPost400ResponseConstraints(obj EmployeesPost400Response) error {
	for _, el := range obj.Details {
		if err := AssertErrorDetailConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
