// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * employee API
 *
 * API для модуля employee
 *
 * API version: 1.0.0
 */

package employeegenerated


import (
	"time"
)



type CreateEmployeeRequest struct {

	FirstName string `json:"firstName"`

	LastName string `json:"lastName"`

	MiddleName *string `json:"middleName,omitempty"`

	Phone string `json:"phone" validate:"regexp=^\\\\+?[1-9]\\\\d{1,14}$"`

	Position *string `json:"position,omitempty"`

	Role string `json:"role,omitempty"`

	BirthDate *string `json:"birthDate,omitempty"`

	HiredAt *time.Time `json:"hiredAt,omitempty"`

	Email string `json:"email"`

	Status *string `json:"status,omitempty"`

	AvatarUrl *string `json:"avatarUrl,omitempty"`
}

// AssertCreateEmployeeRequestRequired checks if the required fields are not zero-ed
func AssertCreateEmployeeRequestRequired(obj CreateEmployeeRequest) error {
	elements := map[string]interface{}{
		"firstName": obj.FirstName,
		"lastName": obj.LastName,
		"phone": obj.Phone,
		"email": obj.Email,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateEmployeeRequestConstraints checks if the values respects the defined constraints
func AssertCreateEmployeeRequestConstraints(obj CreateEmployeeRequest) error {
	return nil
}
