// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * employee API
 *
 * API для модуля employee
 *
 * API version: 1.0.0
 */

package employeegenerated


import (
	"time"
)



type UpdateEmployeeRequest struct {

	FirstName string `json:"firstName,omitempty"`

	LastName string `json:"lastName,omitempty"`

	MiddleName *string `json:"middleName,omitempty"`

	Phone *string `json:"phone,omitempty" validate:"regexp=^\\\\+?[1-9]\\\\d{1,14}$"`

	Position *string `json:"position,omitempty"`

	Role string `json:"role,omitempty"`

	BirthDate *string `json:"birthDate,omitempty"`

	HiredAt *time.Time `json:"hiredAt,omitempty"`

	FiredAt *time.Time `json:"firedAt,omitempty"`

	Email *string `json:"email,omitempty"`

	Status *string `json:"status,omitempty"`

	AvatarUrl *string `json:"avatarUrl,omitempty"`
}

// AssertUpdateEmployeeRequestRequired checks if the required fields are not zero-ed
func AssertUpdateEmployeeRequestRequired(obj UpdateEmployeeRequest) error {
	return nil
}

// AssertUpdateEmployeeRequestConstraints checks if the values respects the defined constraints
func AssertUpdateEmployeeRequestConstraints(obj UpdateEmployeeRequest) error {
	return nil
}
