// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * employee API
 *
 * API для модуля employee
 *
 * API version: 1.0.0
 */

package employeegenerated


import (
	"time"
)



type Employee struct {

	Id int64 `json:"id"`

	FirstName string `json:"firstName"`

	LastName string `json:"lastName"`

	MiddleName *string `json:"middleName,omitempty"`

	Phone string `json:"phone"`

	Position *string `json:"position,omitempty"`

	Role string `json:"role,omitempty"`

	BirthDate *string `json:"birthDate,omitempty"`

	HiredAt *time.Time `json:"hiredAt,omitempty"`

	FiredAt *time.Time `json:"firedAt,omitempty"`

	AddedAt time.Time `json:"addedAt,omitempty"`

	Email string `json:"email"`

	Status string `json:"status,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt time.Time `json:"updatedAt,omitempty"`

	CreatedBy *int64 `json:"createdBy,omitempty"`

	AvatarUrl *string `json:"avatarUrl,omitempty"`
}

// AssertEmployeeRequired checks if the required fields are not zero-ed
func AssertEmployeeRequired(obj Employee) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"firstName": obj.FirstName,
		"lastName": obj.LastName,
		"phone": obj.Phone,
		"email": obj.Email,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertEmployeeConstraints checks if the values respects the defined constraints
func AssertEmployeeConstraints(obj Employee) error {
	return nil
}
