openapi: 3.0.3
info:
  title: business API
  version: 1.0.0
  description: API для модуля business

servers:
  - url: http://localhost:8080/api/v1
    description: Development server

components:
  schemas:
    Business:
      type: object
      required: [id, name, createdAt, updatedAt, ownerFirstName, ownerLastName, ownerEmail, ownerPhone]
      properties:
        id:
          type: integer
          format: uint64
          x-go-type: uint64
          example: 1
        name:
          type: string
          maxLength: 200
          example: "ООО Ромашка"
        description:
          type: string
          nullable: true
        ownerFirstName:
          type: string
          maxLength: 100
          example: "Иван"
        ownerLastName:
          type: string
          maxLength: 100
          example: "Петров"
        ownerMiddleName:
          type: string
          maxLength: 100
          nullable: true
          example: "Иванович"
        ownerEmail:
          type: string
          format: email
          example: "owner@example.com"
        ownerPhone:
          type: string
          example: "+79991234567"
        logoId:
          type: string
          nullable: true
          example: "logo_123"
        createdAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        isWorking:
          type: boolean 
          default: false
          description: Флаг активности
          example: true
        deletedAt:
          type: string
          format: date-time
          nullable: true
        ownerId:
          type: integer
          format: uint64
          x-go-type: uint64
          nullable: true

    CreateBusinessRequest:
      type: object
      required: [name, ownerFirstName, ownerLastName, ownerEmail, ownerPhone, password, passwordConfirmation]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
          example: "ООО Ромашка"
        description:
          type: string
          nullable: true
          example: "ООО Ромашка"
        ownerFirstName:
          type: string
          maxLength: 100
          example: "Иван"
        ownerLastName:
          type: string
          maxLength: 100
        ownerMiddleName:
          type: string
          maxLength: 100
          nullable: true
          example: "Иванович"
        ownerEmail:
          type: string
          format: email
          example: "owner@example.com"
        ownerPhone:
          type: string
          pattern: '^\+?[1-9]\d{1,14}$'
          example: "+79161234567" 
        password:
          type: string
          minLength: 8
          maxLength: 100
          pattern: '^[a-zA-Z0-9]+$'
          description: Пароль для авторизации
          example: "password123"
        passwordConfirmation:
          type: string
          minLength: 8
          maxLength: 100
          pattern: '^[a-zA-Z0-9]+$'
          description: Подтверждение пароля
          example: "password123"

    UpdateBusinessRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 200
          nullable: true
        description:
          type: string
          nullable: true
        ownerFirstName:
          type: string
          maxLength: 100
          nullable: true
        ownerLastName:
          type: string
          maxLength: 100
          nullable: true
        ownerMiddleName:
          type: string
          maxLength: 100
          nullable: true
        ownerEmail:
          type: string
          format: email
          nullable: true
        ownerPhone:
          type: string
          nullable: true
        logoId:
          type: string
          nullable: true
        isWorking:
          type: boolean
          description: Флаг активности
          nullable: true
        ownerId:
          type: integer
          format: uint64
          nullable: true

    ValidationErrorDetail:
      type: object  
      required: [field, message]
      properties:
        field:
          type: string
        message:
          type: string
  
    CreateBusinessResponse:
      type: object  
      required: [data, message] 
      properties:
        data:
          $ref: '#/components/schemas/Business'
        message:
          type: string
          example: "Business created successfully"  

  responses:
    BusinessNotFound:
      description: Бизнес не найден
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Business Not Found"
              message:
                type: string
                example: "Business with ID 123 not found"
    ValidationErrorResponse:
      description: Ошибка валидации
      content:
        application/json:
          schema:
            type: object
            required: [error, message, details]
            properties:
              error:
                type: string
                example: "Validation Error"
              message:
                type: string
                example: "Request validation failed"
              details:
                type: array
                items:
                  $ref: '#/components/schemas/ValidationErrorDetail'

paths:
  /business:
    post:
      summary: Создать бизнес
      description: Создать новый бизнес
      tags: [Businesses]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBusinessRequest'
      responses:
        201:
          description: Бизнес создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateBusinessResponse'
        400:
          $ref: '#/components/responses/ValidationErrorResponse'

  /business/{id}:
    parameters:
      - name: id
        in: path
        required: true  
        schema:
          type: integer
          format: uint64
        description: ID ресурса
    get:
      summary: Получить бизнес по ID
      tags: [Businesses]
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Business'
        404:
          $ref: '#/components/responses/BusinessNotFound'
    put:
      summary: Обновить бизнес
      tags: [Businesses]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBusinessRequest'
      responses:
        200:
          description: Бизнес обновлён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Business'
        404:
          $ref: '#/components/responses/BusinessNotFound'
    delete:
      summary: Удалить бизнес
      tags: [Businesses]
      responses:
        200:
          description: Бизнес удален
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Business deleted successfully"
        404:
          $ref: '#/components/responses/BusinessNotFound' 