openapi: 3.0.3
info:
  title: employee API
  version: 1.0.0
  description: API для модуля employee

servers:
  - url: http://localhost:8080/api/v1
    description: Development server

# Схемы (модели) для сотрудников
components:
  schemas:
  
    Employee:
      type: object
      required: [id, firstName, lastName, email, phone]
      properties:
        id:
          type: integer
          format: int64
          example: 1
        firstName:
          type: string
          maxLength: 100
          example: "Иван"
        lastName:
          type: string
          maxLength: 100
          example: "Петров"
        middleName:
          type: string
          maxLength: 100
          nullable: true
          example: "Иванович"
        phone:
          type: string
          example: "+79161234567"
        position:
          type: string
          nullable: true
          example: "Кассир"
        role:
          type: string
          enum: [regular, admin, owner]
          example: "regular"
        birthDate:
          type: string
          format: date
          nullable: true
          example: "1990-05-20"
        hiredAt:
          type: string
          format: date-time
          nullable: true
          example: "2024-01-15T10:30:00Z"
        firedAt:
          type: string
          format: date-time
          nullable: true
          example: "2025-06-01T18:00:00Z"
        addedAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        email:
          type: string
          format: email
          example: "ivan.petrov@example.com"
        status:
          type: string
          enum: [onboarding, active, vacation, ill]
          example: "onboarding"
        createdAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        createdBy:
          type: integer
          format: int64
          nullable: true
          example: 1
        avatarUrl:
          type: string
          format: uri
          nullable: true
          example: "https://cdn.example.com/avatars/1.png"

    CreateEmployeeRequest:
      type: object
      required:
        - firstName
        - lastName
        - email
        - phone
      properties:
        firstName:
          type: string
          minLength: 1
          maxLength: 100
          example: "Иван"
        lastName:
          type: string
          minLength: 1
          maxLength: 100
          example: "Петров"
        middleName:
          type: string
          maxLength: 100
          nullable: true
          example: "Иванович"
        phone:
          type: string
          pattern: '^\+?[1-9]\d{1,14}$'
          example: "+79161234567"
        position:
          type: string
          nullable: true
          example: "Кассир"
        role:
          type: string
          enum: [regular, admin, owner]
          example: "regular"
        birthDate:
          type: string
          format: date
          nullable: true
          example: "1990-05-20"
        hiredAt:
          type: string
          format: date-time
          nullable: true
          example: "2024-01-15T10:30:00Z"
        email:
          type: string
          format: email
          example: "ivan.petrov@example.com"
        status:
          type: string
          enum: [onboarding, active, vacation, ill]
          nullable: true
          example: "onboarding"
        avatarUrl:
          type: string
          format: uri
          nullable: true
          example: "https://cdn.example.com/avatars/1.png"

    UpdateEmployeeRequest:
      type: object
      properties:
        firstName:
          type: string
          maxLength: 100
          example: "Иван"
        lastName:
          type: string
          maxLength: 100
          example: "Петров"
        middleName:
          type: string
          maxLength: 100
          nullable: true
          example: "Иванович"
        phone:
          type: string
          nullable: true
          pattern: '^\+?[1-9]\d{1,14}$'
          example: "+79161234567"
        position:
          type: string
          nullable: true
          example: "Кассир"
        role:
          type: string
          enum: [regular, admin, owner]
          example: "admin"
        birthDate:
          type: string
          format: date
          nullable: true
          example: "1990-05-20"
        hiredAt:
          type: string
          format: date-time
          nullable: true
          example: "2024-01-15T10:30:00Z"
        firedAt:
          type: string
          format: date-time
          nullable: true
          example: "2025-06-01T18:00:00Z"
        email:
          type: string
          format: email
          nullable: true
          example: "ivan.petrov@example.com"
        status:
          type: string
          enum: [onboarding, active, vacation, ill]
          nullable: true
          example: "active"
        avatarUrl:
          type: string
          format: uri
          nullable: true
          example: "https://cdn.example.com/avatars/1.png"

    EmployeeListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
        pagination:
          $ref: '../components/common.yaml#/components/schemas/Pagination'

  responses:
    EmployeeNotFound:
      description: Сотрудник не найден
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Employee Not Found"
              message:
                type: string
                example: "Employee with ID 123 not found"

# ВСЕ пути для сотрудников в одном месте
paths:
  /employees:
    get:
      summary: Список сотрудников
      description: Получить список сотрудников с пагинацией
      tags: [Employees]
      parameters:
        - $ref: '../components/parameters.yaml#/components/parameters/PageQueryParam'
        - $ref: '../components/parameters.yaml#/components/parameters/LimitQueryParam'
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeListResponse'
    
    post:
      summary: Создать сотрудника
      description: Создать нового сотрудника
      tags: [Employees]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEmployeeRequest'
      responses:
        201:
          description: Сотрудник создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        400:
          $ref: '../components/common.yaml#/components/responses/ValidationError'

  /employees/{id}:
    parameters:
      - $ref: '../components/parameters.yaml#/components/parameters/IdPathParam'
    get:
      summary: Получить сотрудника по ID
      tags: [Employees]
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        404:
          $ref: '#/components/responses/EmployeeNotFound'

    put:
      summary: Обновить сотрудника
      tags: [Employees]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmployeeRequest'
      responses:
        200:
          description: Сотрудник обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        404:
          $ref: '#/components/responses/EmployeeNotFound'

    delete:
      summary: Удалить сотрудника
      tags: [Employees]
      responses:
        204:
          description: Сотрудник удален
        404:
          $ref: '#/components/responses/EmployeeNotFound'