// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * sales API
 *
 * API для модуля sales
 *
 * API version: 1.0.0
 */

package salesgenerated




type SalesReportDailyGet200Response struct {

	Date string `json:"date,omitempty"`

	TotalSales float32 `json:"totalSales,omitempty"`

	TotalItems int32 `json:"totalItems,omitempty"`

	Sales []Sale `json:"sales,omitempty"`
}

// AssertSalesReportDailyGet200ResponseRequired checks if the required fields are not zero-ed
func AssertSalesReportDailyGet200ResponseRequired(obj SalesReportDailyGet200Response) error {
	for _, el := range obj.Sales {
		if err := AssertSaleRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertSalesReportDailyGet200ResponseConstraints checks if the values respects the defined constraints
func AssertSalesReportDailyGet200ResponseConstraints(obj SalesReportDailyGet200Response) error {
	for _, el := range obj.Sales {
		if err := AssertSaleConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
