components:
  parameters:
    IdPathParam:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64
      description: ID ресурса

    PageQueryParam:
      name: page
      in: query
      required: false
      schema:
        type: integer
        format: int32
        default: 1
        minimum: 1
      description: Номер страницы

    LimitQueryParam:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        format: int32
        default: 20
        minimum: 1
        maximum: 100
      description: Количество элементов на странице